server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.253.132:3306/cloud_user?usesSSL=false
    username: root
    password: asdf

  redis:
    host: 192.168.253.132
    port: 6379
    password: asdf
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  elasticsearch:
    rest:
      uris: 192.168.253.132:9200

  application:
    name: cacheservice

  rabbitmq:
    host: 192.168.253.132
    port: 5672
    username: root
    password: asdf
    virtual-host: "/"

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.132:8848

mybatis-plus:
  type-aliases-package: com.example.cachenow.domain

# 配置IK分词器
analyzer:
  class: org.wltea.analyzer.lucene.IKAnalyzer

# 配置分词器工厂
analyzerFactory:
  class: org.springframework.beans.factory.config.MethodInvokingFactoryBean
  properties:
    targetObject: "@analyzer"
    targetMethod: "getTokenizer"

# 配置自定义的分词器
customTokenizer:
  class: com.example.CustomTokenizer
  properties:
    analyzerFactory: "@analyzerFactory"