#文件存储的位置
file:
  upload:
    directory: classpath:upload/

server:
  port: 8081

spring:
  mail:
    default-encoding: UTF-8
    username: "2211087760@qq.com"
    password: "clirqbxdturqdidg"
    host: "smtp.qq.com"

  elasticsearch:
    rest:
      uris: http://192.168.253.132:9200
  datasource:
    url: jdbc:mysql://192.168.253.132:3306/cloud_user?usesSSL=false
    username: root
    password: asdf

  redis:
    host: 192.168.253.132
    port: 6379
    password: asdf
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  application:
    name: cacheservice

  rabbitmq:
    host: 192.168.253.132
    port: 5672
    username: root
    password: asdf
    virtual-host: "/"

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.132:8848

mybatis-plus:
  type-aliases-package: com.example.cachenow.domain


